#!/usr/bin/env python3
"""Inject audit data into one of the HTML decision-tool templates safely.

The HTML templates contain a placeholder line:

    const __AUDIT_DATA__ = /* AUDIT_DATA_INJECTION_POINT */ [];

The data array is generated by sub-agents reading the user's session history.
That data flows across an agent → template boundary and may legitimately contain
characters that look like HTML or JS source — angle brackets, the literal string
"</script>", line-terminator characters U+2028/U+2029. If we splice raw output
into a <script> block we can break the script tag or the JS parse, which is a
classic HTML-injection pitfall.

This script does the only safe thing:

  1. Read the data file as JSON (parsed, not text — invalid JSON fails fast)
  2. Re-serialise via json.dumps — produces canonical JSON, no JS expressions
  3. Post-escape four sequences that JSON allows but a <script> context does not:
       <        ->  <
       >        ->  >
       /        ->  /   (covers </script and ensures no </ in output)
       U+2028   ->      (LINE SEPARATOR, a JS line terminator pre-ES2019)
       U+2029   ->      (PARAGRAPH SEPARATOR, same)
  4. Splice the escaped JSON literal in place of the placeholder

The result is parseable JSON inside <script>, with no possible breakout.

Usage:
    inject-audit-data.py <template.html> <data.json> [--output <out.html>]

If --output is omitted, the populated HTML is written to stdout.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# The placeholder string the templates contain. The injection target is the
# array literal `[]` immediately after the comment marker — we replace from
# the start of the marker line through the end of the placeholder array.
INJECTION_MARKER = "/* AUDIT_DATA_INJECTION_POINT */"

# Defence-in-depth secret redaction. The security-pass agent prompt asks for
# fingerprinted evidence (e.g. `OPENAI_API_KEY=***[redacted, 132 chars]`),
# but a lazy or jailbroken agent might still paste the raw value into the
# `evidence`/`why`/`fix` fields. Without this layer, such a value would land
# in the rendered HTML and ride along through the markdown export to chat /
# the audit-history file. The patterns below catch the formats most likely
# to be misembedded; a string matching is replaced with its prefix +
# `***[redacted, N chars]`. The HTML still shows the user *that* a secret was
# found; the raw bytes never leave the inject step.
_SECRET_PATTERNS: list[tuple[re.Pattern, str]] = [
    # Provider-prefixed keys: OpenAI sk- / sk-proj-, GitHub ghp_/gho_/ghu_/ghs_/ghr_,
    # Slack xoxb-/xoxp-/xoxa-, Google AIza, Anthropic sk-ant-, Stripe sk_live_/rk_live_,
    # AWS AKIA/ASIA. Treat 12+ char run after the prefix as the secret body.
    (re.compile(r"\b(sk-(?:proj-|ant-)?)[A-Za-z0-9_\-]{12,}\b"), r"\1"),
    (re.compile(r"\b(ghp_|gho_|ghu_|ghs_|ghr_)[A-Za-z0-9]{20,}\b"), r"\1"),
    (re.compile(r"\b(xox[bpao]-)[A-Za-z0-9\-]{10,}\b"), r"\1"),
    (re.compile(r"\b(AIza)[A-Za-z0-9_\-]{30,}\b"), r"\1"),
    (re.compile(r"\b(sk_live_|rk_live_|sk_test_)[A-Za-z0-9]{20,}\b"), r"\1"),
    (re.compile(r"\b(AKIA|ASIA)[A-Z0-9]{16,}\b"), r"\1"),
    # Generic key=value pattern: TOKEN=, SECRET=, API_KEY=, PASSWORD=,
    # CREDENTIAL=, AUTH= followed by 12+ non-whitespace chars. Catches
    # arbitrary providers and the env-block format common in settings.json.
    (
        re.compile(
            r"(?i)\b((?:api[_\-]?)?(?:token|secret|key|password|credential|auth)\s*[=:]\s*[\"\']?)([^\s\"\']{12,})",
        ),
        r"\1",
    ),
]


def _redact_string(s: str) -> str:
    """Run the secret-pattern scrubber over one string. Idempotent."""
    if not s or "[redacted" in s:
        return s
    out = s
    for pat, _ in _SECRET_PATTERNS:
        def _repl(match: re.Match) -> str:
            full = match.group(0)
            prefix = match.group(1)
            body_len = len(full) - len(prefix)
            return f"{prefix}***[redacted, {body_len} chars]"
        out = pat.sub(_repl, out)
    return out


def _redact_recursive(value):
    """Walk a JSON-like structure and redact every string in place."""
    if isinstance(value, str):
        return _redact_string(value)
    if isinstance(value, list):
        return [_redact_recursive(v) for v in value]
    if isinstance(value, dict):
        return {k: _redact_recursive(v) for k, v in value.items()}
    return value


def safe_json_for_script(data: object) -> str:
    """Serialise `data` as JSON suitable for embedding inside a <script> tag.

    Two layers of defence:
      1. **Secret redaction** — a regex scrubber masks values matching common
         secret formats (provider-prefixed keys, generic TOKEN=/SECRET=/KEY=
         assignments). The security-pass agent is *asked* to fingerprint
         secrets in its evidence field, but a misbehaving agent might still
         paste the raw value. Catching it here means raw secrets never reach
         the rendered HTML, the markdown export, or the audit-history file.
      2. **Script-context escaping** — escapes the four byte sequences that
         are valid JSON but unsafe in HTML/JS embedding (<, </, U+2028,
         U+2029). See module docstring for the threat model.
    """
    redacted = _redact_recursive(data)
    raw = json.dumps(redacted, ensure_ascii=False, separators=(",", ":"))
    return (
        raw.replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("/", "\\u002f")
        .replace(" ", "\\u2028")
        .replace(" ", "\\u2029")
    )


_OPEN_TO_CLOSE = {"[": "]", "{": "}"}


def find_injection_span(template: str) -> tuple[int, int]:
    """Locate the placeholder literal in the template.

    The placeholder may be either a JSON array `[...]` (skills template) or a
    JSON object `{...}` (rules template). Returns (start, end) covering the
    marker comment plus the balanced literal immediately after it.

    Raises ValueError if the marker is missing or the literal isn't balanced.
    """
    marker_idx = template.find(INJECTION_MARKER)
    if marker_idx < 0:
        raise ValueError(
            f"injection marker {INJECTION_MARKER!r} not found in template — "
            "the template must contain a line of the form "
            "`const __NAME__ = /* AUDIT_DATA_INJECTION_POINT */ [...];` "
            "(or {...} for an object placeholder)"
        )

    # Walk forward to the opening bracket of the placeholder.
    cursor = marker_idx + len(INJECTION_MARKER)
    while cursor < len(template) and template[cursor] not in _OPEN_TO_CLOSE:
        if not template[cursor].isspace():
            raise ValueError(
                "injection marker must be followed by `[` or `{` "
                f"(found {template[cursor]!r} at offset {cursor})"
            )
        cursor += 1
    if cursor >= len(template):
        raise ValueError("injection marker reached end of template before `[` or `{`")

    open_ch = template[cursor]
    close_ch = _OPEN_TO_CLOSE[open_ch]

    # Walk forward over a balanced literal. Track string literals and skip
    # comment ranges so we don't get fooled by close brackets in strings.
    # Both `[`/`]` and `{`/`}` count toward depth — that lets nested objects
    # inside an array placeholder (or nested arrays inside an object) close
    # the outer literal at the right place.
    depth = 0
    in_string: str | None = None  # ' or " or None
    end = cursor
    i = cursor
    while i < len(template):
        ch = template[i]
        if in_string:
            if ch == "\\":
                i += 2
                continue
            if ch == in_string:
                in_string = None
        else:
            if ch in ("'", '"'):
                in_string = ch
            elif ch == open_ch:
                depth += 1
            elif ch == close_ch:
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
            elif ch == "/" and i + 1 < len(template) and template[i + 1] == "/":
                # Line comment — skip to newline.
                nl = template.find("\n", i)
                i = nl if nl != -1 else len(template)
                continue
            elif ch == "/" and i + 1 < len(template) and template[i + 1] == "*":
                # Block comment — skip to */.
                close = template.find("*/", i + 2)
                if close == -1:
                    raise ValueError(
                        "unterminated block comment inside injection placeholder"
                    )
                i = close + 2
                continue
        i += 1

    if depth != 0:
        raise ValueError(
            f"injection placeholder is not a balanced {open_ch}{close_ch} literal "
            "— check the template for stray brackets"
        )

    return marker_idx, end


def inject(template: str, data: object) -> str:
    start, end = find_injection_span(template)
    safe_json = safe_json_for_script(data)
    return template[:start] + INJECTION_MARKER + " " + safe_json + template[end:]


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("template", help="Path to the HTML template")
    p.add_argument("data", help="Path to the JSON file containing the audit data")
    p.add_argument(
        "--output",
        "-o",
        help="Write to this path instead of stdout",
    )
    args = p.parse_args(argv)

    # Wrap file reads with friendly errors. Default Python tracebacks are
    # 12+ lines of internal frames; an end-user sees "FileNotFoundError" and
    # has no idea what to do. The wrapped messages name the missing file
    # and what to check.
    template_path = Path(args.template)
    if not template_path.is_file():
        print(f"template file not found: {args.template}", file=sys.stderr)
        return 2
    try:
        template_text = template_path.read_text(encoding="utf-8")
    except OSError as e:
        print(f"could not read template {args.template}: {e}", file=sys.stderr)
        return 2

    data_path = Path(args.data)
    if not data_path.is_file():
        print(f"audit data file not found: {args.data}", file=sys.stderr)
        return 2
    try:
        data = json.loads(data_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"audit data file is not valid JSON: {e}", file=sys.stderr)
        return 2
    except OSError as e:
        print(f"could not read audit data {args.data}: {e}", file=sys.stderr)
        return 2

    try:
        out = inject(template_text, data)
    except ValueError as e:
        print(f"could not inject: {e}", file=sys.stderr)
        return 2

    if args.output:
        try:
            Path(args.output).write_text(out, encoding="utf-8")
        except OSError as e:
            print(f"could not write output {args.output}: {e}", file=sys.stderr)
            return 2
        print(args.output)
    else:
        sys.stdout.write(out)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
